### ISSUE TITLE
如何本地运行

### ISSUE THREAD

**Issue by trump250** [a893206/campus-micro-blog#1]
怎么在本地运行起来呢

**Comment by trump250** [comment]
Unsatisfied dependency expressed through field 'mailSender'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mailSender' defined in file [D:\桌面\campus-micro-blog\target\classes\com\cr\campusmicroblog\util\MailSender.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
报这个错

**Comment by a893206** [comment]
看README初始化数据库 修改MailSender中的用户名为你的邮箱 启动Redis
